const translations = {
  it: {
    brandSub: 'Agricoltura · Forestazione · Giardinaggio',
    navHome: 'Home',
    navProducts: 'Prodotti',
    navWorkshop: 'Officina',
    navBrands: 'Marchi',
    navContacts: 'Contatti',
    homeEyebrow: 'Lauria · vendita · assistenza',
    homeTitle: 'Macchine, ricambi, officina.',
    homeText: 'Giardinaggio e agricoltura, da due generazioni.',
    call: 'Chiama',
    whatsapp: 'WhatsApp',
    emailAction: 'Email us',
    emailAction: 'Scrivi un’email',
    heroNote: 'Foto futura: facciata, insegna o banco officina.',
    productsLabel: 'Prodotti',
    productsCardTitle: 'Attrezzature selezionate',
    productsCardText: 'Motoseghe, rasaerba, decespugliatori, motozappe, scuotitori e accessori.',
    workshopLabel: 'Officina',
    workshopCardTitle: 'Supporto dopo l’acquisto',
    workshopCardText: 'Riparazioni, manutenzione e ricambi, con un rapporto diretto e pratico.',
    toneLabel: 'Tono del sito',
    toneQuote: 'Strumenti buoni. Supporto vero.',
    catalogLabel: 'Catalogo',
    catalogTitle: 'Prodotti',
    catalogText: 'Una panoramica ordinata delle categorie trattate in negozio.',
    serviceLabel: 'Servizio',
    serviceTitleCard: 'Officina',
    serviceTextCard: 'Riparazioni, manutenzione, ricambi e supporto tecnico.',
    visitLabel: 'Visita',
    visitTitle: 'Contatti',
    visitText: 'Telefono, WhatsApp, indirizzo e mappa del negozio.',
    productsEyebrow: 'Prodotti',
    productsTitle: 'Categorie principali',
    productsIntro: 'Un catalogo essenziale, pensato per orientare e invitare al contatto.',
    cat1: 'Motoseghe',
    cat1Text: 'Taglio e potatura.',
    cat2: 'Rasaerba',
    cat2Text: 'Prato e manutenzione del verde.',
    cat3: 'Decespugliatori',
    cat3Text: 'Per giardino e campagna.',
    cat4: 'Motozappe',
    cat4Text: 'Terreno e orto.',
    cat5: 'Ricambi',
    cat5Text: 'Catene, lame, oli, fili e filtri.',
    cat6: 'Scuotitori',
    cat6Text: 'Raccolta e stagionalità.',
    workshopEyebrow: 'Officina',
    workshopTitle: 'Vendita e assistenza, insieme.',
    workshopIntro: 'Un negozio utile anche dopo l’acquisto: riparazioni, manutenzione e ricambi.',
    workshopNote: 'Foto futura: mani, banco lavoro, dettagli officina.',
    work1: 'Riparazioni',
    work2: 'Manutenzione',
    work3: 'Ricambi e accessori',
    work4: 'Supporto post-vendita',
    callInfo: 'Chiama per info',
    detail1Label: 'Servizio',
    detail1Title: 'Supporto diretto',
    detail1Text: 'Un’impostazione pratica e locale, pensata per seguire il cliente nel tempo.',
    detail2Label: 'Ricambi',
    detail2Title: 'Componenti e consumabili',
    detail2Text: 'Fili, lame, catene, oli, filtri e piccoli ricambi da definire meglio in seguito.',
    detail3Label: 'Placeholder',
    detail3Title: 'Dettagli da completare',
    detail3Text: 'Questa sezione potrà ospitare servizi reali più specifici quando li raccoglierete.',
    brandsEyebrow: 'Marchi',
    brandsTitle: 'Marchi trattati',
    brandsIntro: 'Oleo-Mac in evidenza, con spazio per aggiungere gli altri marchi reali del negozio.',
    featured: 'In evidenza',
    brandText: 'Vendita, ricambi e supporto tecnico.',
    story1Label: 'Impostazione',
    story1Title: 'Marchi selezionati',
    story1Text: 'Questa pagina potrà ospitare una presentazione più precisa dei marchi reali e del loro posizionamento.',
    story2Label: 'Placeholder',
    story2Title: 'Elenco in evoluzione',
    story2Text: 'Per ora lasciamo spazio a futuri inserimenti, senza appesantire il sito con loghi casuali o incompleti.',
    contactsEyebrow: 'Contatti',
    contactsTitle: 'Passa, chiama, scrivi.',
    contactsIntro: 'Contatti rapidi e indirizzo del negozio, senza fronzoli.',
    phoneLabel: 'Telefono',
    contactsBoxTitle: 'Contatti',
    addressLabel: 'Indirizzo',
    addressTitle: 'Lauria',
    addressText: 'Via Rocco Scotellaro 161, 85044 Lauria (PZ), Italia',
    openMap: 'Apri la mappa',
    hoursLabel: 'Orari',
    hoursTitle: 'Apertura',
    hoursText: 'Lun–Sab · 08:30–12:30 / 14:30–18:30',
    footerNote: 'Email e orari possono essere aggiornati facilmente quando avremo i dati definitivi.'
  },
  en: {
    brandSub: 'Agriculture · Forestry · Gardening',
    navHome: 'Home',
    navProducts: 'Products',
    navWorkshop: 'Workshop',
    navBrands: 'Brands',
    navContacts: 'Contacts',
    homeEyebrow: 'Lauria · sales · service',
    homeTitle: 'Machines, parts, workshop.',
    homeText: 'Gardening and agriculture, across two generations.',
    call: 'Call',
    whatsapp: 'WhatsApp',
    emailAction: 'Scrivi un’email',
    heroNote: 'Future photo: storefront, sign or workshop bench.',
    productsLabel: 'Products',
    productsCardTitle: 'Selected equipment',
    productsCardText: 'Chainsaws, lawnmowers, brushcutters, tillers, shakers and accessories.',
    workshopLabel: 'Workshop',
    workshopCardTitle: 'Support after purchase',
    workshopCardText: 'Repairs, maintenance and spare parts, with a direct practical approach.',
    toneLabel: 'Site tone',
    toneQuote: 'Good tools. Real support.',
    catalogLabel: 'Catalogue',
    catalogTitle: 'Products',
    catalogText: 'A clean overview of the categories available in-store.',
    serviceLabel: 'Service',
    serviceTitleCard: 'Workshop',
    serviceTextCard: 'Repairs, maintenance, spare parts and technical support.',
    visitLabel: 'Visit',
    visitTitle: 'Contacts',
    visitText: 'Phone, WhatsApp, address and map.',
    productsEyebrow: 'Products',
    productsTitle: 'Main categories',
    productsIntro: 'An essential catalogue designed to guide and invite contact.',
    cat1: 'Chainsaws',
    cat1Text: 'Cutting and pruning.',
    cat2: 'Lawnmowers',
    cat2Text: 'Lawn and green maintenance.',
    cat3: 'Brushcutters',
    cat3Text: 'For garden and countryside.',
    cat4: 'Tillers',
    cat4Text: 'Soil and garden plots.',
    cat5: 'Spare parts',
    cat5Text: 'Chains, blades, oils, lines and filters.',
    cat6: 'Shakers',
    cat6Text: 'Harvest and seasonal work.',
    workshopEyebrow: 'Workshop',
    workshopTitle: 'Sales and service, together.',
    workshopIntro: 'A useful shop even after the purchase: repairs, maintenance and spare parts.',
    workshopNote: 'Future photo: hands, workbench, workshop details.',
    work1: 'Repairs',
    work2: 'Maintenance',
    work3: 'Spare parts and accessories',
    work4: 'Post-sale support',
    callInfo: 'Call for info',
    detail1Label: 'Service',
    detail1Title: 'Direct support',
    detail1Text: 'A practical local setup designed to support customers over time.',
    detail2Label: 'Spare parts',
    detail2Title: 'Components and consumables',
    detail2Text: 'Lines, blades, chains, oils, filters and small parts to define better later.',
    detail3Label: 'Placeholder',
    detail3Title: 'Details to complete',
    detail3Text: 'This section can later host more specific real services once you collect them.',
    brandsEyebrow: 'Brands',
    brandsTitle: 'Brands carried',
    brandsIntro: 'Oleo-Mac featured, with room to add the shop’s other real brands.',
    featured: 'Featured',
    brandText: 'Sales, spare parts and technical support.',
    story1Label: 'Approach',
    story1Title: 'Selected brands',
    story1Text: 'This page can later host a more precise presentation of the actual brands and their positioning.',
    story2Label: 'Placeholder',
    story2Title: 'List in progress',
    story2Text: 'For now we leave room for future additions, without cluttering the site with random or incomplete logos.',
    contactsEyebrow: 'Contacts',
    contactsTitle: 'Visit, call, write.',
    contactsIntro: 'Quick contact details and address, without clutter.',
    phoneLabel: 'Phone',
    contactsBoxTitle: 'Contacts',
    addressLabel: 'Address',
    addressTitle: 'Lauria',
    addressText: 'Via Rocco Scotellaro 161, 85044 Lauria (PZ), Italy',
    openMap: 'Open map',
    hoursLabel: 'Hours',
    hoursTitle: 'Opening',
    hoursText: 'Mon–Sat · 08:30–12:30 / 14:30–18:30',
    footerNote: 'Email and hours can be updated easily once final details are confirmed.'
  }
};

function applyTranslations(lang) {
  const dict = translations[lang] || translations.it;
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach((el) => {
    const key = el.dataset.i18n;
    if (dict[key]) el.textContent = dict[key];
  });
  document.querySelectorAll('.lang-btn').forEach((btn) => {
    btn.classList.toggle('is-active', btn.dataset.lang === lang);
  });
  localStorage.setItem('shop-language', lang);
  document.querySelectorAll('.email-btn').forEach((btn) => {
    btn.setAttribute('href', lang === 'en' ? btn.dataset.mailtoEn : btn.dataset.mailtoIt);
  });
}

document.addEventListener('DOMContentLoaded', () => {
  document.querySelectorAll('.lang-btn').forEach((btn) => {
    btn.addEventListener('click', () => applyTranslations(btn.dataset.lang));
  });
  applyTranslations(localStorage.getItem('shop-language') || 'it');
});
